[http]
    enable = true
    port = 3000
    addr = "127.0.0.1"
    public = "https://test.com"

[graphql-server]
    enable = true
    port = 5000
    addr = "127.0.0.1"

[database]
    name     = "vulcanize"
    hostname = "localhost"
    port     = 5432
    user     = "postgres"
    password = ""

[graphql]
    uri = "http://localhost:5000"

[watcher]
    event   = true
    header  = true
    storage = true
